### ISSUE TITLE
Version mismatch with pytorch

### ISSUE THREAD

**Issue by RaunakGangi** [TABREZ-96/SnapChef#1]
hey @TABREZ-96 , Firstly thank u very much creating such a nice application.
however, i've been having problems running it
its running successfully but i'm not getting any results when i upload a picture. I'm getting an error somewhat like this
![image](https://github.com/TABREZ-96/SnapChef/assets/87577841/ff57a9da-38e2-4fa2-9bb3-c25128deaa16)
i think its related to pytorch. Couldyou please tell me the version of your python too

**Comment by TABREZ-96** [comment]
Hey, I am using Python 3.10.7
